---
- name: "Create credential..."
  debug: var=credential

- set_fact:
    the_groovy_script: "add-credential.groovy"

- name: "Generate groovy script to add a credential"
  template:
    src: "{{ the_groovy_script }}.j2"
    dest: "/tmp/{{ the_groovy_script }}"
    owner:  "{{ cj_runas_user }}"
    group:  "{{ cj_runas_group }}"

- name: "Execute the script: /tmp/{{ the_groovy_script }}"
  shell: >
    java -jar {{ cj_cli_jar_location }} -s http://{{ cj_cli_hostname }}:{{ cj_http_port }}{{ cj_application_context | default('') }}/ groovy /tmp/{{ the_groovy_script }}
  #ignore_errors: true
  register: result

- name: "Print result"
  debug: var=result.stdout_lines

