---
#  - name: "Find and delete nodes not defined in list 'cj_nodes'"
- set_fact:
    the_groovy_script: "delete-old-nodes.groovy"

- name: "Generate groovy script to remove unknown nodes"
  template:
    src: "{{ the_groovy_script }}.j2"
    dest: "/tmp/{{ the_groovy_script }}"
    owner:  "{{ cj_runas_user }}"
    group:  "{{ cj_runas_group }}"

- name: "Execute the script: /tmp/{{ the_groovy_script }}"
  shell: >
    java -jar {{ cj_cli_jar_location }} -s http://{{ cj_cli_hostname }}:{{ cj_http_port }}{{ cj_application_context | default('') }}/ groovy /tmp/{{ the_groovy_script }}
  register: result

- name: "Create nodes from list 'cj_nodes'"
  set_fact:
    the_groovy_script: "create-nodes.groovy"

- name: "Generate groovy script to create/update nodes"
  template:
    src: "{{ the_groovy_script }}.j2"
    dest: "/tmp/{{ the_groovy_script }}"
    owner:  "{{ cj_runas_user }}"
    group:  "{{ cj_runas_group }}"

- name: "Execute the script: /tmp/{{ the_groovy_script }}"
  shell: >
    java -jar {{ cj_cli_jar_location }} -s http://{{ cj_cli_hostname }}:{{ cj_http_port }}{{ cj_application_context | default('') }}/ groovy /tmp/{{ the_groovy_script }}
  register: result
