---
# tasks file for ansible-role-custom-jenkins
- block:

  - name: "01 :: include Debain / Redhat OS vars"
    include_vars: "{{ ansible_os_family }}.yml"

  - name: "-01 :: in case you want to cleanup the and start over ..."
    include: "cj-cleanup.yml"
    static: no
    when: ((cleanup is defined) and (cleanup | bool))

  - name: "02.1 :: define cj_repo_url fact to {{ cj_repo_url_latest_lts }}"
    set_fact:
      cj_repo_url: "{{ cj_repo_url_latest_lts }}"
    when: cj_channel == 'latest-LTS'

  - name: "02.2 :: Define cj_repo_url fact to {{ cj_repo_url_gratest_n_latest }}"
    set_fact:
      cj_repo_url: "{{ cj_repo_url_gratest_n_latest }}"
    when: cj_channel == 'latest'

  - name: "03 :: Include Debain / Redhat OS installaion method"
    include: "cj-install_{{ ansible_os_family }}.yml"

  - name: "05 :: Configure Jenkins via {{ cj_conf_file }}"
    template:
      src: "jenkins-config-{{ ansible_os_family }}.j2"
      dest: "{{ cj_conf_file }}"
      mode: 0755
    register: config_changed

  - name: "06 :: Configure Jenkins Proxy - if cj_set_proxy is set"
    include: "cj-proxy.yml"
    when: (cj_set_proxy is defined) and (cj_set_proxy | bool)

  - name: "-06 :: Remove proxy config - if cj_remove_proxy is set"
    file:
      dest: "{{ cj_home }}/proxy.xml"
      state: absent
    when: (cj_remove_proxy is defined) and (cj_remove_proxy | bool)

  - name: "08 :: Service start & enable"
    include: "cj-restart-jenkins.yml"

  become: true
  become_user: root

- block:

  - name: "04 :: Validate {{ cj_runas_user d('jenkins')}} has a valid ssh key"
    include: "cj-ssh_key.yml"

  - name: "10 :: install recommanded plugins"
    include: "cj-plugins-online-install.yml"

  - name: "07 :: Configure Jenkins Authentication & Authorization [known to do nothing on 1st run]"
    include: "cj-init_config.yml"

  - name: "08 :: Add ssh public key of {{ cj_runas_user }} user to user {{ cj_local_admin_users[0].username }} properties in Jenkins"
    include: "cj-add-public-key-to-admin-user.yml"

  - name: "09 :: Check auth status"
    include: "cj-auth_check.yml"

  - name: "09.1 :: Cli Login"
    include: "cj-cli-login.yml"

  - name: "Add credentials"
    include: "cj-add-all-credentials.yml"

  - name: "Create Jenkins nodes"
    include: "cj-add-nodes.yml"
    when: ((cj_nodes_create is defined) and (cj_nodes_create | bool))

  - name: "Add JDK-s to tools"
    include: "cj-add-tools-jdks.yml"

  ### configure look & feel
  - name: "11 :: Enable jenkins material theme - if requested config & restart"
    include: "cj-theme.yml"
    when: ((cj_theme is defined) and (cj_theme | bool))
    static: no

  - block:

    - name: "12.1 :: Check auth status"
      include: "cj-auth_check.yml"

    - name: "12.2 :: Cli Login"
      include: "cj-cli-login.yml"

    - name: "12.3 :: Demo seed job(s) - if requested login, delete, import & trigger 1st build"
      include: "cj-seed.yml"

    when: ((cj_seed_demo is defined) and (cj_seed_demo | bool))

  become: true
  become_user: "{{ cj_runas_user }}"

